baseURL = "https://complete-muscle-therapy.netlify.app"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = "true"
languageCode = "en-us"
summaryLength = 25
[[menu.main]]
name = "Massage"
parent = "Services"
url = "/services"
weight = 1
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 2
[[menu.main]]
name = "Testimonials"
url = "/testimonials"
weight = 4
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Services"
url = "/services"
weight = 6
[[menu.main]]
name = "About"
url = "/about"
weight = 3
