baseURL = "https://www.completemuscletherapy.net/"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = "true"
languageCode = "en-us"
summaryLength = 25
[[menu.main]]
name = "Testimonials"
parent = "Resources"
url = "/testimonials"
weight = 2
[[menu.main]]
name = "Blog"
parent = "Resources"
url = "/blog"
weight = 1
[[menu.main]]
name = "Resources"
weight = 5
[[menu.main]]
name = "Pricing"
url = "https://www.completemuscletherapy.net/pricing/"
weight = 3
[[menu.main]]
name = "Massage"
parent = "Services"
url = "/services"
weight = 1
[[menu.main]]
name = "About"
url = "/about"
weight = 2
[[menu.main]]
name = "Services"
url = "/services"
weight = 4
[[menu.main]]
name = "Home"
url = "/"
weight = 1
