baseURL = "https://complete-muscle-therapy.netlify.app"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = "true"
languageCode = "en-us"
[[menu.main]]
name = "About"
url = "/about"
weight = 3
[[menu.main]]
name = "Services"
url = "/services"
weight = 5
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Testimonials"
url = "/testimonials"
weight = 4